---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deconz-pvc
  namespace: deconz
spec:
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 30Gi
  accessModes:
    - ReadWriteMany
